/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bai2;

import static bai2.Bai2.db;
import java.io.BufferedInputStream;
import java.io.BufferedOutputStream;
import java.io.File;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.io.InputStream;
import java.io.OutputStream;
import java.io.Reader;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
/**
 *
 * @author quoct
 */
public class QuanLySinhVien extends javax.swing.JFrame {

    /**
     * Creates new form QuanLySinhVien
     */
    
    private  Statement stm=null;
    private    ResultSet rs=null;
    private Connection cn=null;
    public QuanLySinhVien() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        timkiem = new javax.swing.JDialog();
        jPanel3 = new javax.swing.JPanel();
        txtFindMSSV = new javax.swing.JTextField();
        txtFindTen = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        isCheckFindMSSV = new java.awt.Checkbox();
        isCheckFindTen = new java.awt.Checkbox();
        btnOkFind = new javax.swing.JButton();
        btnCancelFind = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtMSSV = new javax.swing.JTextField();
        txtName = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        btnAdd = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        txtToan = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtLy = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtHoa = new javax.swing.JTextField();
        txtBirthday = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbStudent = new javax.swing.JTable();
        btnCancel = new javax.swing.JButton();
        btnOpenCSDL = new javax.swing.JButton();
        btnFind = new javax.swing.JButton();

        timkiem.setMinimumSize(new java.awt.Dimension(600, 300));
        timkiem.setModal(true);

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Thông tin tìm kiếm"));

        txtFindMSSV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFindMSSVActionPerformed(evt);
            }
        });

        txtFindTen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFindTenActionPerformed(evt);
            }
        });

        jLabel8.setText("MSSV");

        jLabel9.setText("Tên");

        btnOkFind.setText("Ok");
        btnOkFind.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOkFindActionPerformed(evt);
            }
        });

        btnCancelFind.setText("Cancel");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 49, Short.MAX_VALUE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(isCheckFindMSSV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(isCheckFindTen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtFindMSSV, javax.swing.GroupLayout.DEFAULT_SIZE, 184, Short.MAX_VALUE)
                            .addComponent(txtFindTen)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(104, 104, 104)
                        .addComponent(btnOkFind, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addComponent(btnCancelFind, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(56, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(isCheckFindMSSV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtFindMSSV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel8)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtFindTen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(isCheckFindTen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnOkFind)
                    .addComponent(btnCancelFind))
                .addContainerGap(34, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout timkiemLayout = new javax.swing.GroupLayout(timkiem.getContentPane());
        timkiem.getContentPane().setLayout(timkiemLayout);
        timkiemLayout.setHorizontalGroup(
            timkiemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(timkiemLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        timkiemLayout.setVerticalGroup(
            timkiemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, timkiemLayout.createSequentialGroup()
                .addContainerGap(42, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Thông tin sinh viên"));

        jLabel1.setText("Mã số sinh viên");

        jLabel2.setText("Tên sinh viên");

        jLabel3.setText("Ngày sinh");

        txtMSSV.setEnabled(false);
        txtMSSV.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtMSSVKeyReleased(evt);
            }
        });

        txtName.setEnabled(false);

        jLabel4.setText("(dd/mm/yy)");

        btnAdd.setText("Thêm");
        btnAdd.setEnabled(false);
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnUpdate.setText("Sửa");
        btnUpdate.setEnabled(false);
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnDelete.setText("Xóa");
        btnDelete.setEnabled(false);
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        txtToan.setEnabled(false);

        jLabel5.setText("Điểm Toán");

        jLabel6.setText("Điểm Lý");

        txtLy.setEnabled(false);

        jLabel7.setText("Điểm Hóa");

        txtHoa.setEnabled(false);

        txtBirthday.setEnabled(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnAdd)
                        .addGap(50, 50, 50)
                        .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38)
                        .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(9, 9, 9))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 84, Short.MAX_VALUE))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtMSSV, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txtBirthday)
                                            .addComponent(txtName, javax.swing.GroupLayout.DEFAULT_SIZE, 195, Short.MAX_VALUE))))))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel5)
                                .addGap(18, 18, 18)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtToan, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                            .addComponent(txtLy)
                            .addComponent(txtHoa))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMSSV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(txtToan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtLy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addGap(18, 18, 18)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel7)
                    .addComponent(txtHoa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtBirthday, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDelete)
                    .addComponent(btnUpdate)
                    .addComponent(btnAdd))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Danh sách sinh viên"));

        tbStudent.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã số sinh viên", "Tên sinh viên", "Ngày sinh", "Điểm Toán", "Điểm Lý", "Điểm Hóa"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbStudent.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbStudentMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbStudent);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 617, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(346, 346, 346))
        );

        btnCancel.setText("Thoát");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        btnOpenCSDL.setText("Thêm CSDL");
        btnOpenCSDL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOpenCSDLActionPerformed(evt);
            }
        });

        btnFind.setText("Tìm Kiếm");
        btnFind.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFindActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnOpenCSDL, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnFind, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                        .addComponent(btnCancel)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnOpenCSDL)
                            .addComponent(btnFind))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private boolean handleTable(boolean isCheckOnUpdate){
        boolean result=false;
        if(isCheckOnUpdate){
            
            int mssv;
            String name="";
            String ngaysinh="";
            float diemtoan, diemly,diemhoa;
            String sql="select * from student";
            try{
                
                stm=cn.createStatement();
                rs=stm.executeQuery(sql);
                DefaultTableModel row2 = (DefaultTableModel) tbStudent.getModel();
                row2.setRowCount(0);
                tbStudent.clearSelection();
                while(rs.next()){
                    mssv=rs.getInt(1);
                    name=rs.getString(2);
                    ngaysinh=rs.getString(3);
                    diemtoan=rs.getFloat(4);
                    diemly=rs.getFloat(5);
                    diemhoa=rs.getFloat(6);
                    Object[] row = { mssv, name, ngaysinh,diemtoan,diemly,diemhoa };
                    DefaultTableModel model = (DefaultTableModel) tbStudent.getModel();
                    model.addRow(row);
                    }
                result=true;
                }
                catch(Exception e){
                    System.out.println("lại lỗi =(("+ e);
                }
        }
        return result;
    }
    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        String mssv=txtMSSV.getText();
        String name=txtName.getText();
        String birthday=txtBirthday.getText();
        String diemToan=txtToan.getText();
        String diemLy=txtLy.getText();
        String diemHoa=txtHoa.getText();
        if(mssv.equals("")||name.equals("")||birthday.equals("")||diemToan.equals("")||diemLy.equals("")||diemHoa.equals("")){ 
             JFrame frame = new JFrame("JOptionPane showMessageDialog example");
            JOptionPane.showMessageDialog(frame,
                "Vui lòng không được bỏ trống các ô thông tin",
                "Thông báo",
                JOptionPane.ERROR_MESSAGE);
//            System.out.println("trống");
        }else{
            DefaultTableModel model = (DefaultTableModel) tbStudent.getModel();
            int numberRow=tbStudent.getRowCount();
            String saveMSSV;
            boolean result=true;
            for(int i=0;i<numberRow;i++){
                saveMSSV=tbStudent.getValueAt(i,0).toString();
                if(txtMSSV.getText().equals(saveMSSV)){
                          JFrame frame = new JFrame("JOptionPane showMessageDialog example");
                       JOptionPane.showMessageDialog(frame,
                           "Sinh viên có mã số"+txtMSSV.getText()+"đã tồn tại. Vui lòng kiểm tra lại",
                           "Thông báo",
                           JOptionPane.WARNING_MESSAGE);
                       result=false;
                       break;
                   }
                }
            //Kiểm tra ngày sinh có đúng địng dạng không
            if(isValidDate(birthday)==false){
                StringBuilder stringBuilder = new StringBuilder();
                stringBuilder.append("Ngày sinh không đúng định dạng \n");  
                if(stringBuilder.length()>0){
                     JFrame frame = new JFrame("JOptionPane showMessageDialog example");
                  JOptionPane.showMessageDialog(frame,
                      stringBuilder.toString(),
                      "Thông báo",
                      JOptionPane.ERROR_MESSAGE);
                  result=false;
                }
            }
            if(result){
                String sql="INSERT INTO student(mssv,name,ngaysinh,diemtoan,diemly,diemhoa) values ("+mssv+",N'"+name+"','"+birthday+"',"+diemToan+","+diemLy+","+diemHoa+")";
            try{
                Connection cn=db.getConnection();
                Statement stm=null;
                stm=cn.createStatement();
                int n=stm.executeUpdate(sql);
                boolean isCheck=handleTable(true);
                JFrame frame = new JFrame("JOptionPane showMessageDialog example");
            JOptionPane.showMessageDialog(frame,
                "Thêm sinh viên "+mssv+" Thành công",
                "Thông báo",
                JOptionPane.ERROR_MESSAGE);
            }
            catch(Exception e){
                System.out.println("lại lỗi =(("+ e);
            }

            }          
                
        }        
                

        
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        int selectedRow=tbStudent.getSelectedRow();
        String mssv=txtMSSV.getText();
        if(selectedRow>=0){
            DefaultTableModel model = (DefaultTableModel) tbStudent.getModel();
            String name=tbStudent.getValueAt(selectedRow,1).toString();
            int response = JOptionPane.showConfirmDialog (null,
                            "Bạn có muốn xóa sinh viên "+name+" không?"
                               ,"Confirm Overwrite",
                            JOptionPane.OK_CANCEL_OPTION, JOptionPane.QUESTION_MESSAGE);
            if (response == JOptionPane.OK_OPTION){
                
                
                String sql=" Delete from student where mssv="+mssv;
                ;
                try{
                    Statement stm=null;
                    stm=cn.createStatement();
                    int n=stm.executeUpdate(sql);
                    txtBirthday.setText("");
                    txtMSSV.setText("");
                    txtName.setText("");
                    txtToan.setText("");
                    txtLy.setText("");
                    txtHoa.setText("");
                    txtMSSV.setEnabled(true);
                    boolean isCheck=handleTable(true);
                    JFrame frame = new JFrame("JOptionPane showMessageDialog example");
                JOptionPane.showMessageDialog(frame,
                    "Xóa sinh viên "+mssv+" Thành công",
                    "Thông báo",
                    JOptionPane.ERROR_MESSAGE);
                }
                catch(Exception e){
                    System.out.println("lại lỗi =(("+ e);
                }
                boolean isCheck=handleTable(true);
            }          
        }else{
            JFrame frame = new JFrame("JOptionPane showMessageDialog example");
                          JOptionPane.showMessageDialog(frame,
                              "Bạn vui lòng chọn sinh viên trong danh sách!",
                              "Thông báo",
                              JOptionPane.WARNING_MESSAGE);
        }
                   
    }//GEN-LAST:event_btnDeleteActionPerformed


    
    private void txtMSSVKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMSSVKeyReleased

       
    }//GEN-LAST:event_txtMSSVKeyReleased
    //Hàm kiểm tra định dạng ngày sinh
    private boolean isValidDate(String date){
        boolean result=true;
        DateFormat dateFormat = new SimpleDateFormat("dd/MM/yy");
        dateFormat.setLenient(false);
        try{
            Date d = dateFormat.parse(date);
            // string contains valid date
            }
        catch (ParseException ex)            {
            // string contains invalid date
            result=false;
            }
        return result;
    }

    private void tbStudentMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbStudentMouseClicked

       int selectedRow=tbStudent.getSelectedRow();
       txtMSSV.setText(tbStudent.getValueAt(selectedRow,0).toString());
       txtName.setText(tbStudent.getValueAt(selectedRow,1).toString());
       txtBirthday.setText(tbStudent.getValueAt(selectedRow,2).toString());
       txtToan.setText(tbStudent.getValueAt(selectedRow,3).toString());
       txtLy.setText(tbStudent.getValueAt(selectedRow,4).toString());
       txtHoa.setText(tbStudent.getValueAt(selectedRow,5).toString());
       txtMSSV.setEnabled(false);
       
    }//GEN-LAST:event_tbStudentMouseClicked

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        String mssv=txtMSSV.getText();
        
        String name=txtName.getText();
        String birthday=txtBirthday.getText();
        String diemToan=txtToan.getText();
        String diemLy=txtLy.getText();
        String diemHoa=txtHoa.getText();
        int selectedRow=tbStudent.getSelectedRow();
        if(selectedRow>=0){
            if(mssv.equals("")||name.equals("")||birthday.equals("")||diemToan.equals("")||diemLy.equals("")||diemHoa.equals("")){ 
             JFrame frame = new JFrame("JOptionPane showMessageDialog example");
            JOptionPane.showMessageDialog(frame,
                "Vui lòng không được bỏ trống các ô thông tin",
                "Thông báo",
                JOptionPane.ERROR_MESSAGE);
//            System.out.println("trống");
        }else{
            DefaultTableModel model = (DefaultTableModel) tbStudent.getModel();
            int numberRow=tbStudent.getRowCount();
            String saveMSSV;
            boolean result=true;
            //Kiểm tra ngày sinh có đúng địng dạng không
            if(isValidDate(birthday)==false){
                StringBuilder stringBuilder = new StringBuilder();
                stringBuilder.append("Ngày sinh không đúng định dạng \n");  
                if(stringBuilder.length()>0){
                     JFrame frame = new JFrame("JOptionPane showMessageDialog example");
                  JOptionPane.showMessageDialog(frame,
                      stringBuilder.toString(),
                      "Thông báo",
                      JOptionPane.ERROR_MESSAGE);
                  result=false;
                }
            }
            if(result){
                String sql="UPDATE student SET name='"+name+"',ngaysinh='"+birthday+"',diemtoan="+diemToan+",diemly="+diemLy+",diemhoa="+diemHoa+" where mssv="+mssv;
                ;
                try{
                    Statement stm=null;
                    stm=cn.createStatement();
                    int n=stm.executeUpdate(sql);
                    txtBirthday.setText("");
                    txtMSSV.setText("");
                    txtName.setText("");
                    txtToan.setText("");
                    txtLy.setText("");
                    txtHoa.setText("");
                    txtMSSV.setEnabled(true);
                    boolean isCheck=handleTable(true);
                    JFrame frame = new JFrame("JOptionPane showMessageDialog example");
                JOptionPane.showMessageDialog(frame,
                    "Update sinh viên "+mssv+" Thành công",
                    "Thông báo",
                    JOptionPane.ERROR_MESSAGE);
                }
                catch(Exception e){
                    System.out.println("lại lỗi =(("+ e);
                }

            }          
                
        }        
        }else{
            StringBuilder stringBuilder = new StringBuilder();
                stringBuilder.append("Bạn vui lòng chọn sinh viên trong danh sách \n");  
                if(stringBuilder.length()>0){
                     JFrame frame = new JFrame("JOptionPane showMessageDialog example");
                  JOptionPane.showMessageDialog(frame,
                      stringBuilder.toString(),
                      "Thông báo",
                      JOptionPane.WARNING_MESSAGE);
                }
        }
        
        
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnFindActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFindActionPerformed
        timkiem.setVisible(true);
    }//GEN-LAST:event_btnFindActionPerformed

    private void btnOpenCSDLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOpenCSDLActionPerformed
         cn=db.getConnection();
         boolean isCheckUpdate=handleTable(true);
         if(isCheckUpdate){

            btnAdd.setEnabled(true);
            btnUpdate.setEnabled(true);
            btnDelete.setEnabled(true);
            txtBirthday.setEnabled(true);
            txtMSSV.setEnabled(true);
            txtName.setEnabled(true);
            txtHoa.setEnabled(true);
            txtLy.setEnabled(true);
            txtToan.setEnabled(true);
             JFrame frame = new JFrame("JOptionPane showMessageDialog example");
                              JOptionPane.showMessageDialog(frame,
                                  "mở cơ sở dữ liệu thành công",
                                  "Thông báo",
                                  JOptionPane.ERROR_MESSAGE);
            }
            
            
           
        
    }//GEN-LAST:event_btnOpenCSDLActionPerformed

    private void txtFindMSSVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFindMSSVActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFindMSSVActionPerformed

    private void txtFindTenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFindTenActionPerformed
        
    }//GEN-LAST:event_txtFindTenActionPerformed

    private void btnOkFindActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOkFindActionPerformed
      String findName="";
      String findMssv="";
      String sql="select * from student";
      if(isCheckFindTen.getState()||isCheckFindMSSV.getState()){
        if(isCheckFindTen.getState()&&isCheckFindMSSV.getState()){
            findName=txtFindTen.getText();
            findMssv=txtFindMSSV.getText();
            sql="select * from student  where name like N'"+findName+"%'and mssv like '"+findMssv+"%'";
        }else if(isCheckFindTen.getState()){
             findName=txtFindTen.getText();
            sql="select * from student  where name like N'"+findName+"%'";
        }else{
            findMssv=txtFindMSSV.getText();
            sql="select * from student  where mssv like '"+findMssv+"%'";
        }
        System.out.println(sql);
     }
      try{
                int mssv;
                String name="";
                String ngaysinh="";
                float diemtoan, diemly,diemhoa;
                stm=cn.createStatement();
                rs=stm.executeQuery(sql);
                DefaultTableModel row2 = (DefaultTableModel) tbStudent.getModel();
                row2.setRowCount(0);
                tbStudent.clearSelection();
                while(rs.next()){
                    mssv=rs.getInt(1);
                    name=rs.getString(2);
                    ngaysinh=rs.getString(3);
                    diemtoan=rs.getFloat(4);
                    diemly=rs.getFloat(5);
                    diemhoa=rs.getFloat(6);
                    Object[] row = { mssv, name, ngaysinh,diemtoan,diemly,diemhoa };
                    DefaultTableModel model = (DefaultTableModel) tbStudent.getModel();
                    model.addRow(row);
                    }
                }
                catch(Exception e){
                    System.out.println("lại lỗi =(("+ e);
                }
      timkiem.setVisible(false);

    }//GEN-LAST:event_btnOkFindActionPerformed

   
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QuanLySinhVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QuanLySinhVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QuanLySinhVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QuanLySinhVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QuanLySinhVien().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnCancelFind;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnFind;
    private javax.swing.JButton btnOkFind;
    private javax.swing.JButton btnOpenCSDL;
    private javax.swing.JButton btnUpdate;
    private java.awt.Checkbox isCheckFindMSSV;
    private java.awt.Checkbox isCheckFindTen;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbStudent;
    private javax.swing.JDialog timkiem;
    private javax.swing.JTextField txtBirthday;
    private javax.swing.JTextField txtFindMSSV;
    private javax.swing.JTextField txtFindTen;
    private javax.swing.JTextField txtHoa;
    private javax.swing.JTextField txtLy;
    private javax.swing.JTextField txtMSSV;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtToan;
    // End of variables declaration//GEN-END:variables
}
